let civs = [
  {
    name: 'ROME',
    adjective: 'Roman',
    cityNmaes: [
      "Washington",
      "New York",
      "Boston",
      "Philadelphia",
      "Los Angeles",
      "Atlanta",
      "Chicago",
      "St. Louis",
      "Detroit",
      "New Orleans",
      "Baltimore",
      "Denver",
      "Cincinnati",
      "Dallas",
      "Houston",
      "San Antonio",
      "San Francisco",
      "Fresno",
      "Seattle",
      "Portland",
      "Miami",
      "Las Vegas",
      "Cleveland",
      "Toledo",
      "Pittsburgh",
      "Salt Lake City",
      "San Diego",
      "Phoenix",
      "Minneapolis",
      "St. Paul",
      "Kansas City",
      "Buffalo",
      "Syracuse",
      "Wichita",
      "Indianapolis",
      "Orlando",
      "Omaha",
      "Baton Rouge"
    ],
    color: 0xFFB399
  }
]