let abilities = [
  {
    name: 'Militaristic',
    freeTech: 2,
    effect1: 'reduced military improvement costs',
    effect2: 'battlefied promotions'
  },
  {
    name: 'Commercial',
    freeTech: 1,
    effect1: 'extra commerce city center',
    effect2: 'lower corruption'
  },
  {
    name: 'Expansionist',
    freeTech: 0,
    effect1: 'scout',
    effect2: 'better huts'
  },
  {
    name: 'Scientific',
    freeTech: 4,
    effect1: 'free tech each era',
    effect2: 'reduced science improvement'
  },
  {
    name: 'Religious',
    freeTech: 6,
    effect1: 'reduced religious improvement',
    effect2: 'no anarchy'
  },
  {
    name: 'Industrious',
    freeTech: 5,
    effect1: 'faster work',
    effect2: 'extrea production city center'
  }

]


let civs = [
  {
    name: 'America',
    adjective: 'American',
    cityNames: [
      "Washington",
      "New York",
      "Boston",
      "Philadelphia",
      "Los Angeles",
      "Atlanta",
      "Chicago",
      "St. Louis",
      "Detroit",
      "New Orleans",
      "Baltimore",
      "Denver",
      "Cincinnati",
      "Dallas",
      "Houston",
      "San Antonio",
      "San Francisco",
      "Fresno",
      "Seattle",
      "Portland",
      "Miami",
      "Las Vegas",
      "Cleveland",
      "Toledo",
      "Pittsburgh",
      "Salt Lake City",
      "San Diego",
      "Phoenix",
      "Minneapolis",
      "St. Paul",
      "Kansas City",
      "Buffalo",
      "Syracuse",
      "Wichita",
      "Indianapolis",
      "Orlando",
      "Omaha",
      "Baton Rouge"
    ],
    color: 0x2e86c1,
    abilities: [2, 5]
  },
  {
    name: 'Rome',
    ajective: 'Roman',
    cityNames: ['Rome', 'Venice', 'Florance', 'Pisa',
      "Roma",
      "Capua",
      "Veii",
      "Beneventum",
      "Corfinium",
      "Ancona",
      "Tarentum",
      "Brundisium",
      "Ravenna",
      "Pisae",
      "Genua",
      "Mediolanum",
      "Aquileia",
      "Florentia",
      "Bononia",
      "Verona",
      "Ostia (ocean)",
      "Neapolis",
      "Pompeii",
      "Salernum",
      "Perusia",
      "Ariminum",
      "Patavium",
      "Pisae",
      "Cortona",
      "Arretium",
      "Placentia",
      "Rhegium",
      "Altinum",
      "Velia",
      "Asculum Picenum",
      "Herculaneum",
    ],
    color: 0xc0392b,
    abilities: [0, 1]
  },
  {
    name: 'China',
    ajective: 'Chinese',
    cityNames: [
      "Beijing",
      "Shanghai",
      "Guangzhou",
      "Tianjin",
      "Nanjing",
      "Xi'an",
      "Chongqing",
      "Chengdu",
      "Jinan",
      "Shijiazhuang",
      "Taiyuan",
      "Zhengzhou",
      "Wuhan",
      "Changsha",
      "Nanchang",
      "Hangzhou",
      "Fuzhou",
      "Hefei",
      "Guiyang",
      "Lanzhou",
      "Kunming",
      "Xining",
      "Nanning",
      "Yinchuan",
      "Shenyang",
      "Changchun",
      "Harbin",
      "Luoyang",
      "Kaifeng",
      "Qingdao",
      "Suzhou",
      "Wuxi",
      "Xiamen",
      "Haikou",
      "Hong Kong",
      "Datong",
      "Anyang",
      "Shangqiu",
      "Nanyang",
      "Dengfeng"
    ],
    color: 0x7d3c98,
    abilities: [0, 5]
  },
  {
    name: 'Greece',
    ajective: 'Greek',
    cityNames: [
      "Athinai",
      "Sparti",
      "Thivai",
      "Korinthos",
      "Konstandinoupolis",
      "Militos",
      "Efesos",
      "Peiraiefs",
      "Argos",
      "Megalopolis",
      "Elefsis",
      "Chalkis",
      "Eretreia",
      "Thessaloniki",
      "Edessa",
      "Nikopolis",
      "Nafpaktos",
      "Patrai",
      "Olymbia",
      "Pylos",
      "Nafplion",
      "Mykinai",
      "Epidavros",
      "Avlis",
      "Orchomenos",
      "Marathon",
      "Delfoi",
      "Thermopylai",
      "Faliron",
      "Nikaia",
      "Iraklion",
      "Potidaia",
      "Stagira",
      "Olynthos",
      "Kolofon",
    ],
    color: 0x229954,
    abilities: [1, 3]
  },
  {
    name: 'India',
    ajective: 'Indian',
    cityNames: [
      "Delhi",
      "Mumbai",
      "Chennai",
      "Bangalore",
      "Kolkata",
      "Ahmedabad",
      "Kanpur",
      "Hyderabad",
      "Lucknow",
      "Varanasi",
      "Chandigarh",
      "Madurai",
      "Coimbatore",
      "Kozhikode",
      "Thiruvananthapuram",
      "Nagpur",
      "Amritsar",
      "Srinagar",
      "Agra",
      "Bhopal",
      "Patna",
      "Surat",
      "Jaipur",
      "Varanasi",
      "Allahabad",
      "Indore",
      "Mysore",
      "Raipur",
    ],
    color: 0xf1c40f,
    abilities: [1, 4]
  },
  {
    name: 'Persia',
    ajective: 'Persian',
    cityNames: [
      "Teheran",
      "Isfahan",
      "Tabriz",
      "Hamadan",
      "Rasht",
      "Ahraz",
      "Shiraz",
      "Kerman",
      "Yazd",
      "Mashhad",
      "Zahedan",
      "Bushehr",
      "Qazrin",
      "Lhasa",
      "Bulgar",
      "Hormuz",
      "Mosul",
      "Herat",
      "Drapsaka",
      "Karmana",
      "Pura",
      "Bishapur",
      "Ardashir Khureh",
      "Tikni",
      "Istakhr",
      "Shurkutir",
      "Susia",
    ],
    color: 0xdc7633,
    abilities: [3, 5]
  },
  {
    name: 'France',
    ajective: 'French',
    cityNames: [
      "Paris",
      "Lyon",
      "Marseille",
      "Lille",
      "Toulouse",
      "Nice",
      "Bordeaux",
      "Nantes",
      "Strasbourg",
      "Toulon",
      "Rennes",
      "Rouen",
      "Grenoble",
      "Montpellier",
      "Metz",
      "Versailles",
      "Nancy",
      "Clermont-Ferrand",
      "Valenciennes",
      "Tours",
      "Caen",
      "Orléans",
      "Angers",
      "Dijon",
      "Fort-de-France",
      "Saint-Étienne",
      "Brest",
      "Le Havre",
      "Le Mans",
      "Reims",
      "Avignon",
      "Mulhouse",
      "Amiens",
      "Béthune",
    ],
    color: 0x7f8c8d,
    abilities: [0, 5]
  },
  {
    name: 'England',
    ajective: 'English',
    cityNames: [
      "London",
      "Westminster",
      "Birmingham",
      "Liverpool",
      "Manchester",
      "Leeds",
      "York",
      "Newcastle",
      "Canterbury",
      "Bradford",
      "Derby",
      "Southampton",
      "Middlesbrough",
      "Sheffield",
      "Nottingham",
      "Coventry",
      "Bath",
      "Bristol",
      "Brighton",
      "Portsmouth",
      "Hull",
      "Leicester",
      "Plymouth",
      "Bournemouth",
      "Sunderland",
      "Stoke-on-Trent",
      "Bolton",
      "Norwich",
      "Oxford",
      "Colchester",
      "Reading",
      "Cambridge",
      "Gloucester",
      "Blackpool",
      "Stratford-upon-Avon",
      "Durham",
      "Eastleigh",
      "Winchester",
    ],
    color: 0x2c3e50,
    abilities: [1, 2]
  },
  {
    name: 'Russia',
    ajective: 'Russian',
    cityNames: [
      "Moskva",
      "Sankt-Peterburg",
      "Tver",
      "Velikiy Novgorod",
      "Yekaterinburg",
      "Samara",
      "Pskov",
      "Ryazan",
      "Vladimir",
      "Yaroslavl",
      "Novosibirsk",
      "Smolensk",
      "Bryansk",
      "Oryol",
      "Voronezh",
      "Saransk",
      "Perm",
      "Ufa",
      "Saratov",
      "Volgograd ",
      "Tomsk",
      "Petrozavodsk",
      "Rostov-na-Donu",
      "Omsk",
      "Chelyabinsk",
      "Irkutsk",
      "Vladivostok",
      "Khabarovsk",
      "Krasnoyarsk",
      "Suzdal",
      "Vologda",
      "Murmansk",
      "Arkhangelsk",
      "Krasnodar",
      "Stavropol",
      "Murom",
      "Kaluga",
      "Tula",
      "Kursk",
      "Tambov",
    ],
    color: 0xecf0f1,
    abilities: [2, 3]
  }
]